name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Sjekk ut prosjektet
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      # Sett opp Python
      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # Installer avhengigheter
      - name: Installer avhengigheter
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Sjekk koden med flake8
      - name: Sjekk koden med Flake8
        run: |
          pip install flake8
          flake8 .

      # Kjør tester med pytest
      - name: Kjør tester med Pytest
        run: |
          pip install pytest
          pytest
