name: Python Code Quality Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Installer Flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Sjekk koden med Flake8
        run: flake8 .
