name: Python CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Sjekk ut prosjektet
      - name: Sjekk ut koden
        uses: actions/checkout@v3

      # Sett opp Python
      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
