name: CI Workflow

on:
  push:
    branches:
      - main  # Trigges når du gjør en push til 'main'-grenen (endre etter behov)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Sjekk ut repoet for å ha tilgang til koden
      - name: Sjekk ut koden
        uses: actions/checkout@v3
      # Sett opp Node.js (kan endres avhengig av språk/teknologi)
      - name: Sett opp Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Angi versjon etter behov
      # Installer avhengigheter
      - name: Installer avhengigheter
        run: npm install
      # Kjør tester
      - name: Kjør tester
        run: npm test
      # Valgfritt: Kjøre en linter
      - name: Kjør linter
        run: npm run lint  # Endre til linter-kommandoen som passer ditt prosjekt
